[package]
name = "guard"
version = "0.1.0"
description = "mCaptcha - a PoW-based CAPTCHA system"
homepage = "https://mcaptcha.org"
repository = "https://github.com/mCaptcha/guard"
documentation = "https://mcaptcha.org/docs/"
lisense = "AGPLv3 or later version"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"
default-run = "guard"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "guard"
path = "./src/main.rs"

[[bin]]
name = "tests-migrate"
path = "./src/tests-migrate.rs"

[dependencies]
actix-web = "3.3.2"
actix = "0.10"
actix-identity = "0.3"
actix-http = "2.2"
actix-rt = "1"
actix-cors = "0.5.4"
actix-service = "1.0.6"

csrf = "0.4.0"

mime_guess = "2.0.3"
rust-embed = "5.9.0"
cache-buster = { version = "0.1.0", git = "https://github.com/realaravinth/cache-buster" }

futures = "0.3.14"

sqlx = { version = "0.4.0", features = [ "runtime-actix-rustls", "postgres" ] }
argon2-creds = { version = "0.2", git = "https://github.com/realaravinth/argon2-creds", commit = "61f2d1d" }

config = "0.11"
validator = { version = "0.13", features = ["derive"]}

derive_builder = "0.10"
derive_more = "0.99"

serde = "1"
serde_json = "1"
serde_yaml = "0.8.17"

url = "2.2"

pretty_env_logger = "0.4"
log = "0.4"

lazy_static = "1.4"


# m_captcha = { version = "0.1.2", git = "https://github.com/mCaptcha/mCaptcha" }
m_captcha = { branch = "master", git = "https://github.com/mCaptcha/mCaptcha" }

rand = "0.8"

sailfish = "0.3.2"

[build-dependencies]
serde_yaml = "0.8.17"
serde = "1"
serde_json = "1"
yaml-rust = "0.4.5"
cache-buster = { version = "0.1.0", git = "https://github.com/realaravinth/cache-buster" }
mime = "0.3.16"
log = "0.4"
config = "0.11"
url = "2.2"

[dev-dependencies]
pow_sha256 = { version = "0.2.1", git = "https://github.com/mcaptcha/pow_sha256" }
