version: '3.9'

services:
  mcaptcha:
    build: .
    ports:
      - 7000:7000
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres # set password at placeholder
      MCAPTCHA_REDIS_URL: redis://mcaptcha-redis/
      RUST_LOG: debug

  postgres:
    image: postgres:13.2
    volumes:
      - mcaptcha-data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: password # change password
      PGDATA: /var/lib/postgresql/data/mcaptcha/

  mcaptcha-redis:
    image: mcaptcha/cache:latest

volumes:
  mcaptcha-data:
